project:
  type: website
  output-dir: _site

website:
  title: "What is Tatenori?"
  site-url: "https://ats4u.github.io/tatenori-jp/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



