project:
  type: website
  output-dir: _site

website:
  title: "縦乗りとは何か"
  site-url: "https://tatenori.jp/"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: introduction.qmd
format:
  html:
    theme:
      light : [ cosmo, theme.scss ]
      dark : [ brand, theme-dark.scss ]
    css: styles.css
    toc: true
    toc-location: right
    font:
      text: "Dela Gothic One"
      



