project:
  type: website
  output-dir: _site
  # 👇 This part is crucial
  site-url: "https://ats4u.github.io/tatenori-jp/"

website:
  title: "quarto-html1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



